// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHunpaG9fbCmA6aA4J8fKnl8L1UkWK450',
    appId: '1:525412824352:web:0a660f73c5cf964ec09345',
    messagingSenderId: '525412824352',
    projectId: 'mobprog-c692c',
    authDomain: 'mobprog-c692c.firebaseapp.com',
    storageBucket: 'mobprog-c692c.firebasestorage.app',
    measurementId: 'G-R490BJZ7X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJoKvDQW2qCQTjpESW4ErRHRdZT0t8eps',
    appId: '1:525412824352:android:5319abae5745b13ec09345',
    messagingSenderId: '525412824352',
    projectId: 'mobprog-c692c',
    storageBucket: 'mobprog-c692c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHunpaG9fbCmA6aA4J8fKnl8L1UkWK450',
    appId: '1:525412824352:web:d955e712f62de45bc09345',
    messagingSenderId: '525412824352',
    projectId: 'mobprog-c692c',
    authDomain: 'mobprog-c692c.firebaseapp.com',
    storageBucket: 'mobprog-c692c.firebasestorage.app',
    measurementId: 'G-RGWGCZ8112',
  );
}
